/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_javnce_vnc_server_platform_Win32GdiFramebuffer */

#ifndef _Included_org_javnce_vnc_server_platform_Win32GdiFramebuffer
#define _Included_org_javnce_vnc_server_platform_Win32GdiFramebuffer
#ifdef __cplusplus
extern "C" {
#endif
    /*
     * Class:     org_javnce_vnc_server_platform_Win32GdiFramebuffer
     * Method:    hasGdiFramebuffer
     * Signature: ()Z
     */
    JNIEXPORT jboolean JNICALL Java_org_javnce_vnc_server_platform_Win32GdiFramebuffer_hasGdiFramebuffer
    (JNIEnv *, jobject);

    /*
     * Class:     org_javnce_vnc_server_platform_Win32GdiFramebuffer
     * Method:    size
     * Signature: ()Lorg/javnce/rfb/types/Size;
     */
    JNIEXPORT jobject JNICALL Java_org_javnce_vnc_server_platform_Win32GdiFramebuffer_size
    (JNIEnv *, jobject);

    /*
     * Class:     org_javnce_vnc_server_platform_Win32GdiFramebuffer
     * Method:    format
     * Signature: ()Lorg/javnce/rfb/types/PixelFormat;
     */
    JNIEXPORT jobject JNICALL Java_org_javnce_vnc_server_platform_Win32GdiFramebuffer_format
    (JNIEnv *, jobject);

    /*
     * Class:     org_javnce_vnc_server_platform_Win32GdiFramebuffer
     * Method:    buffer
     * Signature: (IIII)[Ljava/nio/ByteBuffer;
     */
    JNIEXPORT jobjectArray JNICALL Java_org_javnce_vnc_server_platform_Win32GdiFramebuffer_buffer
    (JNIEnv *, jobject, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
